site_name: sommelier
site_author: dolfno
site_description: lets keep you inventory up to date

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
